### ISSUE TITLE
Improve set-up for library

### ISSUE THREAD

**Issue by amlcurran** [novoda/download-manager#11]
Currently requires a class which is accessed through reflection _and_ a manifest placeholder. Consider using a Gradle plug-in or similar to do this?

**Comment by friedger** [comment]
using a plugin to use a library seems not the right way. Better go for convention:
$applicationId.downloads is the authority by default. If the user of the app doesn't like that he can add some code.

**Comment by blundell** [comment]
you can't get the clients application id from the library code. Or show here code how? :smile:

**Comment by mr-archano** [comment]
@amlcurran could you elaborate further on:

> Currently requires a class which is accessed through reflection

I thought the only thing needed was specifying the authority (could be a resource). What am I missing?

**Comment by amlcurran** [comment]
The authority is required for URI matching (which is initialised statically). So no resources, unless we change all the URIs to be instance fields

**Comment by blundell** [comment]
https://github.com/novoda/download-manager/blob/master/library/src/main/java/com/novoda/downloadmanager/lib/DownloadProvider.java#L64

&

https://github.com/novoda/download-manager/blob/master/library/src/main/AndroidManifest.xml#L20

**Comment by friedger** [comment]
I don't see a reason why URI matching should be initialised statically (besides performance). If we get rid of the static field we can use the `Context` for defining the authority

**Comment by blundell** [comment]
Yes that is one solution, however there are a lot of fields using the static when you follow the chaining so it'd need indepth testing. We are also at the moment inline with the system DownloadManager and making this chain would be a big separation ... which is fine just we need to justify it.

**Comment by friedger** [comment]
here to see the impact... https://github.com/novoda/download-manager/pull/13

**Comment by xrigau** [comment]
Related #151
