### ISSUE TITLE
Queuing no longer works

### ISSUE THREAD

**Issue by amlcurran** [novoda/download-manager#121]
1. Set-up two downloads 
2. Pause the first download - *the second one starts downloading*
3. Resume the first download - *the first download goes to "Queued"*
4. Pause the second download

What should happen:
The first download should resume again

What does happen:
It says queued and no more downloads occur

**Comment by xrigau** [comment]
the pain is real

**Comment by amlcurran** [comment]
FUN TIMES only seems to happen in client app, might be because we're using batches

**Comment by amlcurran** [comment]
#124 fixed it - did actually download but the UI and notification didn't update
