### ISSUE TITLE
Consider public interface

### ISSUE THREAD

**Issue by blundell** [novoda/download-manager#14]
What classes with @hide should be not visible? Perhaps we should add some sub packages

**Comment by xrigau** [comment]
:+1:

**Comment by amlcurran** [comment]
Noticed that now we've moved `DownloadManager.Query` and `DownloadManager.Request` into their own classes, but the names are too generic now (just `Query` and `Request`)

**Comment by amlcurran** [comment]
Integration point: this will make MUBI fail to compile for now: 56af54471a2dd52ff6e60de72f37e085058ed543

**Comment by amlcurran** [comment]
Fixed by #16
