### ISSUE TITLE
download notification removed then appeared when remove app from recent app list

### ISSUE THREAD

**Issue by hassan379** [novoda/download-manager#143]
hi , thx for this great library , i am facing issue that every time when i try to download something , when press home button and remove the app from recent app list , the download in notification removed and reapeared ,in addition , the notification stuck at downloading state and not showing any update on progress bar 
thx in advance

**Comment by blundell** [comment]
Thanks @hassan379 we do have an upcoming load of work on the Notifications and we should be looking at all these errors

**Comment by xrigau** [comment]
Fixed in #167 and #170
