### ISSUE TITLE
Notify the Activity when Download completed

### ISSUE THREAD

**Issue by z-zghiba** [novoda/download-manager#187]
Notify the Activity when Download completed 
Thanks

**Comment by Dorvaryn** [comment]
Hi if you are asking on how to get the notification when the download finishes the simple demo [here](https://github.com/novoda/download-manager/blob/master/demo-simple/src/main/java/com/novoda/downloadmanager/demo/simple/MainActivity.java) should show it in action.

**Comment by Dorvaryn** [comment]
If you have further issues, try and more detail to your issue. It is difficult to understand what the issue is with such a short message.

**Comment by z-zghiba** [comment]
yes I saw the demo but what I want is to show automatically download status without clicking clicking on the main_refresh_button

**Comment by Dorvaryn** [comment]
For a continuous update you need to use the contentResolver to look at the progress info. There is an example of that [here](https://github.com/novoda/download-manager/blob/master/demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/pause_resume/PauseResumeActivity.java)

**Comment by z-zghiba** [comment]
Thanks.
 I 'll try that

**Comment by z-zghiba** [comment]
Thanks @Dorvaryn it's work
