### ISSUE TITLE
COLUMN_TOTAL_SIZE_BYTES + COLUMN_BYTES_DOWNLOADED_SO_FAR

### ISSUE THREAD

**Issue by z-zghiba** [novoda/download-manager#188]
Hello,
It's normaly that **COLUMN_BYTES_DOWNLOADED_SO_FAR** and **COLUMN_TOTAL_SIZE_BYTES** 
changed only when download is complated and sometimes the COLUMN_TOTAL_SIZE_BYTES  stuck on -1??
This is my code to get the values :
 
```
int id = cursor.getInt(cursor.getColumnIndexOrThrow(DownloadManager.COLUMN_ID));

String title = cursor.getString(cursor.getColumnIndexOrThrow(DownloadManager.COLUMN_TITLE));

int status = cursor.getInt(cursor.getColumnIndexOrThrow(DownloadManager.COLUMN_STATUS));

long totalBytes = cursor.getLong(cursor.getColumnIndexOrThrow(DownloadManager.COLUMN_TOTAL_SIZE_BYTES));

long currentBytes = cursor.getLong(cursor.getColumnIndexOrThrow(DownloadManager.COLUMN_BYTES_DOWNLOADED_SO_FAR));

String latestUpdate = DateFormat.getInstance().format(new Date(Long.valueOf(cursor.getString(
                   cursor.getColumnIndexOrThrow(DownloadManager.COLUMN_LAST_MODIFIED_TIMESTAMP)))));
```

**Comment by rock3r** [comment]
I suppose it's happening because the content size is not known in advance. Is the [`content-length`](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.13) specified in the HTTP response headers if you do the `GET` manually? If it is, then there's a bug, but it seems to work for us.

**Comment by z-zghiba** [comment]
Ok Thank you
