### ISSUE TITLE
Still, there is WRITE Permission Error on internal folder, Please Help!!!

### ISSUE THREAD

**Issue by alveru** [novoda/download-manager#190]
Hello !

I have been struggling with this error for two days now, 

I am getting the following error in my application when setting to use the internal app directory:

Exception: need WRITE_EXTERNAL_STORAGE permission to use DESTINATION_FILE_URI: uid 10134 does not have android.permission.WRITE_EXTERNAL_STORAGE

Why do I need this permission on Android Marshmallow if I am using the internal app data folder?

Am I doing something wrong? I am using this version of library:

compile 'com.novoda:download-manager:0.2.38'

Thanks !!

**Comment by alveru** [comment]
> Hello !
> 
> I have been struggling with this error for two days now,
> 
> I am getting the following error in my application when setting to use the internal app directory:
> 
> Exception: need WRITE_EXTERNAL_STORAGE permission to use DESTINATION_FILE_URI: uid 10134 does not have android.permission.WRITE_EXTERNAL_STORAGE
> 
> Why do I need this permission on Android Marshmallow if I am using the internal app data folder?
> 
> Am I doing something wrong? I am using this version of library:
> 
> compile 'com.novoda:download-manager:0.2.38'
> 
> Thanks !!

e

**Comment by duduBaiao** [comment]
Hi @alveru! Did you have success handling this situation?

I have the same error here.

**Comment by blundell** [comment]
Looks like the library needs an update for Marshmallow, @zegnus @lgvalle do your use cases cover this?
Can it be reproduced in the demo app?

**Comment by duduBaiao** [comment]
@blundell it seems that the app checks for paths starting with "/data" to consider them as internal.

I think that we need an additional check for paths that are public, and don't require permission, like the path returned from this call:

Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);

**Comment by eduardb** [comment]
@duduBaiao Could you, please, add the snippet of code that is causing you problems? Thank you.
