### ISSUE TITLE
Concurrent downloads

### ISSUE THREAD

**Issue by duduBaiao** [novoda/download-manager#191]
Hi! I have a doubt about concurrent downloads.

It is required to use explicit batches to download more than one file simultaneously?

I'm calling "downloadManager.enqueue", but the files are being downloaded serially.

**Comment by blundell** [comment]
Have you set this property in the manifest:

https://github.com/novoda/download-manager/blob/master/demo-extended/src/main/AndroidManifest.xml#L47-L49
```
    <meta-data
      android:name="com.novoda.downloadmanager.MaxConcurrentDownloads"
      android:value="5" />
```

I think it defaults to 1

**Comment by xrigau** [comment]
yeah @duduBaiao what @blundell said is the right thing to do - keep in mind that batches are a way to define multiple files as a unique download but doesn't have to do with concurrency, it just says 'instead of showing 3 files group them as 1 download (batch)'

**Comment by duduBaiao** [comment]
Yes @blundell. I did that, but without success.

The files are enqueued, but the download starts one by time. :(

Thanks for the clarification @xrigau!

**Comment by blundell** [comment]
@duduBaiao can you reproduce your issue using the repo demo?

**Comment by duduBaiao** [comment]
@blundell yes (more or less...). Since the simple demo downloads a single file, I have started a download, stopped the app, changed the url and started another download. 

I could confirm the behavior: the second download started only after the first finishing.

**Comment by blundell** [comment]
yes but that's because the simple demo uses the value of 1 for concurrent downloads, i was asking if you edit it to your usecase does it still work?
