### ISSUE TITLE
Question Download Start, Download finish and Downloading Byte/s  

### ISSUE THREAD

**Issue by z-zghiba** [novoda/download-manager#195]
There is a easy way to know Download Start, Download finish and Downloading Byte/s ?

**Comment by blundell** [comment]
Take a look at the simple demo:

https://github.com/novoda/download-manager/blob/master/demo-simple/src/main/java/com/novoda/downloadmanager/demo/simple/MainActivity.java

This shows start and finish.

It queries the `DownloadManager` in the ASyncTask:

https://github.com/novoda/download-manager/blob/master/demo-simple/src/main/java/com/novoda/downloadmanager/demo/simple/QueryForDownloadsAsyncTask.java#L34-L37

and you can get the number of bytes downloaded so far by querying the cursor for one more column:

https://github.com/novoda/download-manager/blob/master/library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java#L173

**Comment by z-zghiba** [comment]
I don't see how to detect the start download without going through the state PENDING

**Comment by z-zghiba** [comment]
the idea is to detect the download time for each file

**Comment by blundell** [comment]
realtime time detection or after the fact?

Because you know when a download ends with: https://github.com/novoda/download-manager/blob/master/library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java#L179

**Comment by z-zghiba** [comment]
This is  last time modification,  wath i search is to calculate downloading time (stopTime-startTime= downloadingTime) for each file

**Comment by blundell** [comment]
if you look through the extended demo you can set up Broadcast receivers for download batches starting:

https://github.com/novoda/download-manager/blob/master/demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/DownloadBatchStartedReceiver.java

and finishing:

https://github.com/novoda/download-manager/blob/master/demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/DownloadBatchCompletionReceiver.java
