### ISSUE TITLE
Can't download to SD Card

### ISSUE THREAD

**Issue by Hackmodford** [novoda/download-manager#201]
My app downloads audiobooks from a server. I have given the user the option to choose a preferred storage method. If the user chooses their SD card I would like to download files to their SD card instead of internal memory.

When I set the download path to the SD card using request.setDestinationUri. The download fails with an unknown error.

This is the path I am trying to use.
/storage/external_SD/Android/data/com.hughesmedia.big_finish/files/Download

Is there some limitation that I'm not aware of?

Thanks

**Comment by Hackmodford** [comment]
I turned on verbos logging and got this result.

`11-25 10:11:28.647 W/EasyPermissions: hasPermissions: API version < M, returning true by default
11-25 10:11:30.544 V/DownloadManager: initiating download with UID 10014 
11-25 10:11:30.584 V/DownloadManager: Service onCreate 
11-25 10:11:30.585 I/DownloadManager: in removeSpuriousFiles 
11-25 10:11:30.586 I/DownloadManager: in trimDatabase 
11-25 10:11:30.586 V/DownloadManager: starting query, database is not null; projection[0] is _id; selection is status >= '200'; selectionArgs is null; sort is last_modified_timestamp. 
11-25 10:11:30.590 V/DownloadManager: created cursor android.database.sqlite.SQLiteCursor@16c4cb2 on behalf of 29450 
                                      
                                      --------- beginning of amazon_main
11-25 10:11:30.595 D/DownloadManager: invalid selection [(control is null or control = ? ) AND (status = ? or status = ?)) GROUP BY (batch_id] triggered java.lang.IllegalArgumentException: unrecognized column or keyword 
11-25 10:11:30.596 V/DownloadManager: starting query, database is not null; projection[0] is DISTINCT batch_id; selection is (control is null or control = ? ) AND (status = ? or status = ?)) GROUP BY (batch_id; selectionArgs[0] is 0; selectionArgs[1] is 192; selectionArgs[2] is 189; sort is null. 
11-25 10:11:30.599 V/DownloadManager: created cursor android.database.sqlite.SQLiteCursor@1e271403 on behalf of 29450 
11-25 10:11:30.605 V/DownloadManager: Service onStart 
11-25 10:11:30.607 V/DownloadManager: starting query, database is not null; projection is null; selection is null; selectionArgs is null; sort is _id ASC. 
11-25 10:11:30.609 V/DownloadManager: created cursor android.database.sqlite.SQLiteCursor@23d319b9 on behalf of 29450 
11-25 10:11:30.614 V/DownloadManager: processing inserted download 1 
11-25 10:11:30.618 V/DownloadManager: processing inserted download 2 
11-25 10:11:30.623 V/DownloadManager: processing inserted download 3 
11-25 10:11:30.632 V/DownloadManager: processing inserted download 4 
11-25 10:11:30.638 V/DownloadManager: processing inserted download 5 
11-25 10:11:31.684 I/Kernel: [155967.181813]-(0)[30159:arch_worker]dpi vsync
11-25 10:11:32.078 I/art: Background partial concurrent mark sweep GC freed 69546(4MB) AllocSpace objects, 0(0B) LOS objects, 25% free, 11MB/15MB, paused 1.255ms total 139.813ms
11-25 10:11:32.493 V/DownloadManager: starting query, database is not null; projection[0] is status; selection is batch_id = ?; selectionArgs[0] is 5; sort is null. 
11-25 10:11:32.495 V/DownloadManager: created cursor android.database.sqlite.SQLiteCursor@368cc00a on behalf of 29450 
11-25 10:11:32.541 V/DownloadManager: starting query, database is not null; projection[0] is status; selection is null; selectionArgs is null; sort is null. 
11-25 10:11:32.544 V/DownloadManager: starting query, database is not null; projection is null; selection is null; selectionArgs is null; sort is _id ASC. 
11-25 10:11:32.550 V/DownloadManager: created cursor android.database.sqlite.SQLiteCursor@3970de98 on behalf of 29450 
11-25 10:11:32.555 V/DownloadManager: processing inserted download 1 
11-25 10:11:32.559 V/DownloadManager: created cursor android.database.sqlite.SQLiteCursor@1a7146f1 on behalf of 29450 
11-25 10:11:32.562 V/DownloadManager: processing inserted download 2 
11-25 10:11:32.571 V/DownloadManager: starting query, database is not null; projection[0] is control; projection[1] is status; selection is null; selectionArgs is null; sort is null. 
11-25 10:11:32.575 V/DownloadManager: processing inserted download 3 
11-25 10:11:32.577 V/DownloadManager: created cursor android.database.sqlite.SQLiteCursor@153ed2d6 on behalf of 29450 
11-25 10:11:32.578 V/DownloadManager: processing inserted download 4 
11-25 10:11:32.580 V/DownloadManager: processing inserted download 5 
11-25 10:11:32.624 V/DownloadManager: starting query, database is not null; projection is null; selection is null; selectionArgs is null; sort is _id ASC. 
11-25 10:11:32.625 V/DownloadManager: starting query, database is not null; projection[0] is status; selection is batch_id = ?; selectionArgs[0] is 5; sort is null. 
11-25 10:11:32.628 V/DownloadManager: created cursor android.database.sqlite.SQLiteCursor@17812957 on behalf of 29450 
11-25 10:11:32.630 V/DownloadManager: created cursor android.database.sqlite.SQLiteCursor@2ce14c44 on behalf of 29450 
11-25 10:11:32.647 V/DownloadManager: processing inserted download 1 
11-25 10:11:32.658 V/DownloadManager: processing inserted download 2 
11-25 10:11:32.661 V/DownloadManager: processing inserted download 3 
11-25 10:11:32.676 V/DownloadManager: processing inserted download 4 
11-25 10:11:32.676 I/DownloadManager: Download 5 starting 
11-25 10:11:32.679 V/DownloadManager: processing inserted download 5 
11-25 10:11:32.719 V/DownloadManager: starting query, database is not null; projection is null; selection is null; selectionArgs is null; sort is _id ASC. 
11-25 10:11:32.722 V/DownloadManager: created cursor android.database.sqlite.SQLiteCursor@1c2612d on behalf of 29450 
11-25 10:11:32.734 V/DownloadManager: processing inserted download 1 
11-25 10:11:32.737 V/DownloadManager: processing inserted download 2 
11-25 10:11:32.739 V/DownloadManager: processing inserted download 3 
11-25 10:11:32.742 V/DownloadManager: processing inserted download 4 
11-25 10:11:32.745 V/DownloadManager: processing inserted download 5 
11-25 10:11:33.686 W/art: Suspending all threads took: 39.780ms
11-25 10:11:33.783 W/DownloadManager: Exception for id 5: invalid combination of destination: 4, path: /storage/sdcard1/Android/data/com.hughesmedia.big_finish/files/Download/dwmr035-ish.ab2.zip java.lang.IllegalStateException: invalid combination of destination: 4, path: /storage/sdcard1/Android/data/com.hughesmedia.big_finish/files/Download/dwmr035-ish.ab2.zip 
11-25 10:11:33.800 I/BIGFINISH_TAG: Reason: 1000
11-25 10:11:33.801 V/DownloadManager: starting query, database is not null; projection is null; selection is null; selectionArgs is null; sort is _id ASC. 
11-25 10:11:33.803 V/DownloadManager: created cursor android.database.sqlite.SQLiteCursor@f2d4662 on behalf of 29450 
11-25 10:11:33.806 V/DownloadManager: processing inserted download 1 
11-25 10:11:33.807 V/DownloadManager: processing inserted download 2 
11-25 10:11:33.808 V/DownloadManager: starting query, database is not null; projection[0] is status; selection is batch_id = ?; selectionArgs[0] is 5; sort is null. 
11-25 10:11:33.809 V/DownloadManager: processing inserted download 3 
11-25 10:11:33.811 V/DownloadManager: created cursor android.database.sqlite.SQLiteCursor@138503f3 on behalf of 29450 
11-25 10:11:33.811 V/DownloadManager: processing inserted download 4 
11-25 10:11:33.815 V/DownloadManager: processing inserted download 5 
11-25 10:11:33.828 V/DownloadManager: starting query, database is not null; projection is null; selection is null; selectionArgs is null; sort is _id ASC. 
11-25 10:11:33.833 V/DownloadManager: created cursor android.database.sqlite.SQLiteCursor@17c8e8b0 on behalf of 29450 
11-25 10:11:33.836 V/DownloadManager: processing inserted download 1 
11-25 10:11:33.838 V/DownloadManager: processing inserted download 2 
11-25 10:11:33.840 V/DownloadManager: processing inserted download 3 
11-25 10:11:33.841 V/DownloadManager: processing inserted download 4 
11-25 10:11:33.848 V/DownloadManager: processing inserted download 5 
11-25 10:11:33.855 D/DownloadManager: Shutting down service 
11-25 10:11:33.863 I/DownloadManager: Download 5 finished with status UNKNOWN_ERROR 
11-25 10:11:33.901 I/MaliEGL: [Mali]window_type=1, is_framebuffer=0, errnum = 0
11-25 10:11:33.901 I/MaliEGL: [Mali]surface->num_buffers=4, surface->num_frames=3, win_min_undequeued=1
11-25 10:11:33.901 I/MaliEGL: [Mali]max_allowed_dequeued_buffers=3
11-25 10:11:33.904 D/DownloadManager: Shutting down service 
11-25 10:11:33.905 V/DownloadManager: Service onDestroy 
11-25 10:11:56.064 I/Kernel: [155991.567881]-(0)[29450:edia.big_finish]dpi vsync
11-25 10:12:52.413 D/CRLSetManager: getInstance binder: android.os.BinderProxy@c489f76
11-25 10:13:13.294 I/Kernel: [156068.790402]-(0)[29460:JDWP]dpi vsync
11-25 10:13:57.994 I/Kernel: [156113.498185]-(0)[29460:JDWP]dpi vsync
11-25 10:16:38.649 D/BIGFINISH_TAG: onDestroy MediaPlayerService
11-25 10:16:38.675 D/BIGFINISH_TAG: giveUpAudioFocus
11-25 10:16:44.005 D/CRLSetManager: getInstance binder: android.os.BinderProxy@c489f76`

I'm guessing this is the line that is causing me problems.

`11-25 10:11:33.783 W/DownloadManager: Exception for id 5: invalid combination of destination: 4, path: /storage/sdcard1/Android/data/com.hughesmedia.big_finish/files/Download/dwmr035-ish.ab2.zip java.lang.IllegalStateException: invalid combination of destination: 4, path: /storage/sdcard1/Android/data/com.hughesmedia.big_finish/files/Download/dwmr035-ish.ab2.zip`

**Comment by Hackmodford** [comment]
It looks like the StorageManager.java isn't setup to check if the path matches all of the dir that getExternalDirs can return. I'm going to see if modifying the code will solve my problem.

**Comment by ouchadam** [comment]
hey @Hackmodford thanks for reporting this! Could you give an example of how you're setting the path?

**Comment by Hackmodford** [comment]
Sure! Long story short, I'm using this to get the path.

```
public static ArrayList<File> getSDCardDirs(Context context)
    {
        ArrayList<File> dirs = new ArrayList<>();
        final File[] externalDirs = context.getExternalFilesDirs(null);
        for (File dir : externalDirs)
        {
            if (dir != null)
            {
                if (android.os.Build.VERSION.SDK_INT >= 21) {
                    if (Environment.isExternalStorageRemovable(dir)) {
                        dirs.add(dir);
                    }
                } else {
                    dirs.add(dir);
                }
            }
        }
        return dirs;
    }
```

Then using setDestinationUri.

`setDestinationToPreferredStorageDir(request, (String) response.body().get("filename"));`

```
    private Request setDestinationToPreferredStorageDir(Request request, String subPath) {
        final File file = new File(FileHelper.getPreferredStorageDirectory(mContext), Environment.DIRECTORY_DOWNLOADS);
        if (file.exists()) {
            if (!file.isDirectory()) {
                throw new IllegalStateException(file.getAbsolutePath() + " already exists and is not a directory");
            }
        } else {
            if (!file.mkdirs()) {
                throw new IllegalStateException("Unable to create directory: " + file.getAbsolutePath());
            }
        }
        setDestinationFromBase(request, file, subPath);
        return request;
    }

    private void setDestinationFromBase(Request request, File base, String subPath) {
        if (subPath == null) {
            throw new NullPointerException("subPath cannot be null");
        }
        request.setDestinationUri(new File(base, subPath).toURI());
    }
```

**Comment by Hackmodford** [comment]
If I want to modify the code myself, can I import the project as a module? I'm willing to play with it, but I'm having difficulty getting it into a state I can mess with.

**Comment by ouchadam** [comment]
thanks for that, maybe @Hutch4 can chip in as I know he's been looking into external storage paths recently.

You can definitely include this directly in your project by cloning the repo and linking the `library` module to your current gradle configuration `settings.gradle` and app dependencies `compile project(':library')`

**Comment by Hackmodford** [comment]
My experiment worked. I can submit a pull request, but I'm afraid it might be kind of rough. Do you want me to just post my changes here instead?

**Comment by Hackmodford** [comment]
I have created a new pull request to fix this. #204

**Comment by xrigau** [comment]
💯 nicely documented, thanks for submitting the PR @Hackmodford 👍

**Comment by Hackmodford** [comment]
Pull request merged.
