### ISSUE TITLE
Quick return warning

### ISSUE THREAD

**Issue by Mecharyry** [novoda/download-manager#253]
## Problem
We have a few quick return statements in `v2` that can lead to silent failures, no notifications to dev or client application that the flow is incorrect.

## Solution
As a minimum we should surface a warning log when this happens, or if we want to be more aggressive throw an exception. 

## Example
In `CallbackThrottleByTime` we have:

```
        if (timerTask == null) {
            return;
        }
```

so if we don't call `setCallback` when we trigger an update nothing will happen, no warnings, it will just silently do nothing.

**Comment by Aiuspaktyn** [comment]
Same problem, on Android 5.1.1

**Comment by zegnus** [comment]
Yes, this would be a `DeveloperError`

**Comment by MechaRyRy** [comment]
Addressed in the above.
