### ISSUE TITLE
DownloadFileId.from() static ctors are not consistent

### ISSUE THREAD

**Issue by ataulm** [novoda/download-manager#256]
```java
    private final int id;

    public static DownloadFileId from(Batch batch) {
        String id = batch.getTitle() + String.valueOf(System.nanoTime());
        return new DownloadFileId(id.hashCode());
    }

    public static DownloadFileId from(String id) {
        return new DownloadFileId(Integer.valueOf(id));
    }

    private DownloadFileId(int id) {
        this.id = id;
    }
```

We should highlight that `DownloadField.from(Batch)` will likely generate a different ID, even if the client passes the same `Batch`.

This is distinct from the other `from` method, which will generate the same ID if the same string is passed each time.

The second one will **fail** in my understanding if a String that does not represent an integer is passed, but the first allows any parameter. It assumes that the second one should not be used except to recreate an ID that was previously created with a `DownloadBatch`, but there is no distinction in the naming.

Suggest:

- simplifying this class by removing the static ctors. The first one is only used in `DownloadBatchFactory` and the uniqueness requirement could be moved there.
- the second ctor takes a String and parses it to an int - this adds responsibility to this class but the class doesn't live up to the responsibility. Removing this ctor and exposing the int ctor would mean that the conversion to int should be done at the client side: in this case, reading the value from Room as an int so it fails at the earliest level:

```java
class RoomFile {

    @NonNull
    @PrimaryKey
    @ColumnInfo(name = "file_id")
    String id; // change this to int
```

**Comment by zegnus** [comment]
The first method is meant to be use when a new id is created.

The second one is meant to be use to restore that previous id from the database, this is why they take different parameters.

We should definitely clarify this and also yup, we can change the database to hold an int 👍

**Comment by MechaRyRy** [comment]
This no longer exists.

**Comment by ataulm** [comment]
Woo
