### ISSUE TITLE
Move LiteDownloadManager to another package

### ISSUE THREAD

**Issue by ataulm** [novoda/download-manager#257]
LiteDownloadManager is meant to be the default instance of the download manager, if the client doesn't want to customise anything.

A lot of the methods in the library are package protected, so it's cheating if we keep LiteDownloadManager in the same package.

If we moved it to its own, we'd be able to identify whether it's possible to customise all the parts we want customised. Anything that needs to stay in the same package is not customisable and shouldn't be marked with the "Lite" name.

**Comment by zegnus** [comment]
Yup we could try to do that.

How's is done currently is that if you look at the visibility of all the classes in the project you will see public and non public.

All public ones are meant to be used one way or another by the client of the library, the non-public ones are not. Based on this, we could move things to packages if that doesn't mean to expose things that we should not.

Also, there is no exposure of any specific implementation. We only expose contracts.

**Comment by ataulm** [comment]
This comment will be updated with instances where a class prefixed with `Lite` uses classes or methods that are meant to be internal to the library.

---

LiteDownloadService uses `downloadBatch.status()` which returns `InternalDownloadBatchStatus`
