### ISSUE TITLE
Use int for Identifiers

### ISSUE THREAD

**Issue by MechaRyRy** [novoda/download-manager#305]
## Problem

In #303 `hashcode` is used as the identifier for the notification id. Calculating a hash on the `main-thread` for large objects is not very performant, especially when we know this value will remain constant.

## Solution
Use `int` for our ids in the library so that we can easily pass it to the notification manager rather than performing a heavy task on the `main-thread` to create an int using `hashcode`.

**Comment by tasomaniac** [comment]
Any reason for closing? Not that important?

**Comment by MechaRyRy** [comment]
Ah actually I closed this one by accident, this is still an issue 😢

**Comment by MechaRyRy** [comment]
I think this is redundant now. We have an adequate workaround, which is to use the `DownloadBatchStatus.id` as the notification id. https://github.com/novoda/download-manager/blob/release/library/src/main/java/com/novoda/downloadmanager/DownloadBatchStatusNotificationCreator.java
