### ISSUE TITLE
Duplicate files across batches

### ISSUE THREAD

**Issue by MechaRyRy** [novoda/download-manager#313]
### Problem
At the moment it is possible for batches to contain the same files but they only appear as a single file in the storage. So if you delete one batch that contains this file and another batch contains it then you won't be able to access this file 😬 

### Solution
We should allow files to exists across batches. Easiest solution would be to create a directory per batch.

**Comment by danybony** [comment]
This was implemented in https://github.com/novoda/download-manager/pull/334
