### ISSUE TITLE
Add proguard configuration

### ISSUE THREAD

**Issue by ataulm** [novoda/download-manager#352]
should DLM provide a proguard configuration to keep required files? I know it's possible but I can't remember if it's recommended or not (from the community, having tried it).

e.g. for
`-keep class * extends android.arch.persistence.room.RoomDatabase`

**Comment by zegnus** [comment]
Yes, we should provide it 👍

**Comment by MechaRyRy** [comment]
We have a custom configuration https://github.com/novoda/download-manager/blob/release/library/proguard-rules.pro
