### ISSUE TITLE
Creating instance using Kotlin: Type DownloadManager! is inaccessible in this context

### ISSUE THREAD

**Issue by aclassen** [novoda/download-manager#377]
Creating an instance of `LiteDownloadManagerCommands` in Kotlin shows the following IDE warning:

> Type DownloadManager! is inaccessible in this context due to: public/*package*/ open class DownloadManager : LiteDownloadManagerCommands defined in com.novoda.downloadmanager in file DownloadManager.class

The code compiles without any problems and runs fine.
Bytecode is also ok:
```
LINENUMBER 32 L5
INVOKEVIRTUAL com/novoda/downloadmanager/DownloadManagerBuilder.build ()Lcom/novoda/downloadmanager/DownloadManager;
DUP
LDC "DownloadManagerBuilder\n \u2026\n                .build()"
INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkExpressionValueIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
CHECKCAST com/novoda/downloadmanager/LiteDownloadManagerCommands
```
But decompiled Bytecode is showing uncompilable code (but that`s up to the decompiler):
```
DownloadManager var10003 = DownloadManagerBuilder.newInstance((Context)application, new Handler(Looper.getMainLooper()), 2131492865).build();
Intrinsics.checkExpressionValueIsNotNull(var10003, "DownloadManagerBuilder\n …\n                .build()");
```

Long story short , maybe `build()` can return `LiteDownloadManagerCommands` instead of `DownloadManager` ?

**Comment by MechaRyRy** [comment]
Hi @aclassen I assume you have been building this locally to test 😄 I hadn't noticed we weren't coding against the interface for that builder, I will update it today.

**Comment by MechaRyRy** [comment]
@aclassen are you happy to close this issue now?
