### ISSUE TITLE
Remove system DOWNLOAD_WITHOUT_NOTIFICATION permission

### ISSUE THREAD

**Issue by amlcurran** [novoda/download-manager#38]
Currently downloading without a notification uses a system permission - but this download manager is not a system service (unlike the AOSP one). We should investigate if it is required, or at the very least namespace the permission to a novoda namespace

**Comment by blundell** [comment]
@ronocod you did something about this on your branch?

**Comment by ronocod** [comment]
Yeah, as far as I remember we're removing that as it makes no sense when the library is external to the OS. If anyone wanted to bypass the permission they could just fork the repo and remove it.

**Comment by amlcurran** [comment]
I don't even think download without notification will work reliably because our downloadmanager can get killed (the system one can't). So perhaps we should remove this feature, or at least do some investigation

**Comment by Dorvaryn** [comment]
@amlcurran We will need the ability to download without a notification for our project.
Maybe we should investigate this.
