### ISSUE TITLE
Possible race condition in `ThenPerform`

### ISSUE THREAD

**Issue by aclassen** [novoda/download-manager#380]
There 's a possible race condition between `waitForLock` in `ThenPerform` and `DownloadManager` `waitForDownloadService.notifyAll();`

If an instance of  `ThenPerform` is created with a `null` DownloadService and `notifyAll` is called before `waitForLock` is called.

In case the Single Thread Executor is used like : `executor.submit(() -> Wait.<Void>waitFor(downloadService, waitForDownloadService)`

the executor is deadlocked.

**Comment by zegnus** [comment]
Hey @aclassen thank you for your feedback. Looking at the code I found this race condition highly unlikely.

For a deadlock to happen something like this must happen:
1. `DownloadManager.getAllDownloadBatchStatuses()` null instance, `waitForLock` is about to be executed
2. `DownloadManager.initialise()` is called, `notifyAll` that's on a `synchronized` block is about to be called

Only if the `waitForLock` and `notifyAll` methods are swapped at execution time we'll have a deadlock but I don't think that this is a realistic scenario.

Have you been able to reproduce this issue? Do you have any suggestions?

**Comment by aclassen** [comment]
Sorry, for late feedback. 
Yes i was able to reproduce the issue. 
Will try to reproduce with sample app and provide more info.

**Comment by MechaRyRy** [comment]
@aclassen Have you been able to reproduce this issue with the sample app? We'd like to try and resolve this issue as soon as possible if it is still present.

**Comment by aclassen** [comment]
I'll update to latest version next days and try to replicate , if that`s ok for you?

**Comment by MechaRyRy** [comment]
That would be great @aclassen. There's also a PR currently open for the `Wait.Then` that we will try and release this week.

**Comment by aclassen** [comment]
@Mecharyry I tested with latest master branch and i`m not able to reproduce the issue anymore. 👍
