### ISSUE TITLE
What is the status of version 2?

### ISSUE THREAD

**Issue by Hackmodford** [novoda/download-manager#401]
Is version 2 ready for an app in the store? Or should I still stick with version 1?

Is it difficult to migrate to version 2? And how does one do this? Which branch should I use?

The library is awesome, I'm just getting worried about having to use API <= 25 since google seems like they're not going to allow it in the future.

**Comment by MechaRyRy** [comment]
Hi @Hackmodford version two is still in development. We are currently working on the `Migration` process, once that is finished we will be releasing a stable version 2. I personally would like to see a stable version released by the end of this month. I will try and keep you updated, we understand that we need to get this finished so that others can support the more recent versions of android.

**Comment by MechaRyRy** [comment]
Hi @Hackmodford, sorry we weren't able to deliver version 2 by the end of June. We've been trying to improve the file persistence layer and improve how we handle SD cards and the migration. If all goes well we should be releasing v2 within the next couple of weeks. Sorry again.

**Comment by Hackmodford** [comment]
No problem. It's an awesome library and I wish I had the skills to help 😀

I appreciate that you got back to me!

—
Brandon Butler (Hackmodford)

**Comment by MechaRyRy** [comment]
@Hackmodford I'm pleased to announce that version 2 of the `download-manager` has been released.

**Comment by joelfernandes19** [comment]
@Mecharyry Is there a migration guide available? (Migrating from 0.3.0 to 2.0.0)

**Comment by MechaRyRy** [comment]
Hi @joelfernandes19 there isn't currently. I'm going to try and write one over the next few days. I would suggest taking a look at the [MigrationJob](https://github.com/novoda/download-manager/blob/release/demo-simple/src/main/java/com/novoda/downloadmanager/demo/migration/MigrationJob.java) in the meantime.

**Comment by Hackmodford** [comment]
So besides the migration job, are there any big changes in the API we should be aware of?

**Comment by zegnus** [comment]
@Hackmodford Is a completely new API, way easier to integrate with that in the version one. We started from zero and so the design is completely different.

We'll provide a README and an extensive demo app with examples of how to use it all. You'll be able to go as simple as you want using default implementations provided for you by the library, or as complex as you need you providing custom implementations for your notifications, your persistence level, etc..

**Comment by joelfernandes19** [comment]
@Mecharyry @zegnus I understand that v2 has been built from scratch, and believe it's in its early stages, but I was wondering if you guys are planning to make the lib backward compatible? I've been using version 0.3.0 in one of my production apps, and integrating v2 breaks the entire app altogether. 

For example, in the previous release version, there was "COLUMN_EXTRA_DATA", which doesn't exist in v2.

This is one of the reasons why I was asking for a documentation that helps us migrate from v0.3.0 to v2.

**Comment by MechaRyRy** [comment]
The library is not designed to be backwards compatible, it should be fairly straight forward to migrate from one version to the other. Until we have completed the documentation for migration I would again suggest you take a look at the `MigrationJob` and the [`Extractors`](https://github.com/novoda/download-manager/blob/release/demo-simple/src/main/java/com/novoda/downloadmanager/demo/migration/CompletedDownloadBatchesExtractor.java). 

These `Extractors` should look familiar as they deal directly with `v0.3.0`s database. You should just need to extract the information from `v0.3.0` to satisfy the `CompletedDownloadBatch` and `VersionOnePartialDownloadBatch`, which you can then pass to the `DownloadManager` in the same way we do for the samples `MigrationJob`. Unfortunately I cannot provide more help than that at the moment. We are working on a `Migration` doc that will include an example database and how to go about performing a migration.

**Comment by MechaRyRy** [comment]
`v2` has been released, closing.
