### ISSUE TITLE
Is the BroadcastReceiver gone?

### ISSUE THREAD

**Issue by Hackmodford** [novoda/download-manager#434]
In version 2, how do I get notified that a download completed? When a download completes, my app needs to do some processing of the files. In the previous version, this was done via a broadcast receiver. Is there a way to do this in v2?

**Comment by rock3r** [comment]
Not an expert on DM2, but for what I understood all the broadcasts have been replaced with callbacks. See https://blog.novoda.com/download-manager-v2/

**Comment by Hackmodford** [comment]
Thanks for pointing out the article! I got that they're using callbacks and I really like that, but what will reactivate the app when it’s finished? Do I need to wrap the callbacks in a service or something?

**Comment by MechaRyRy** [comment]
Hi @Hackmodford 😄 We have indeed dropped support for the `Broadcast Receiver`, as @rock3r says you'll need to use the `callbacks`. The `download-manager` uses a foreground service to download and deliver notifications and is tied to your application. So when it is downloading / notifying your application will be kept alive. If you are doing any file processing as a result of a notification you may want to create your own service to handle that part as there is no guarantee that the `download-manager` service will continue to exist.

**Comment by Hackmodford** [comment]
@Mecharyry What about if someone closes the app (by swiping up)? What happens to a completed download in that scenario? I would assume the callback never gets called because the app is no longer in memory, right?

**Comment by rock3r** [comment]
If you have a foreground service, swiping the app from the recents won't force close it, and won't interrupt the service, in theory.

**Comment by Hackmodford** [comment]
Okay. So far I'm liking the changes, it seems much cleaner this time around. The other question I had is about instantiation of the downloadManager.

```downloadManager = DownloadManagerBuilder
                .newInstance(this, handler, R.mipmap.ic_launcher_round)
                .withLogHandle(new DemoLogHandle())
                .withStorageRequirementRules(StorageRequirementRuleFactory.createByteBasedRule(TWO_HUNDRED_MB_IN_BYTES))
                .build();
```

If my downloads are typically 500MB - 2GB, do I need to request 2GB of storage space? I'm not sure what this is doing.

Also, is the authority from v1 still required?

**Comment by zegnus** [comment]
Hi @Hackmodford glad you like the new version.

For the space, nope. That's the space that you want free in your phone after a download has finished. This is for preventing to fill up your entire storage with the side effects of collapsing your phone and crashing. You can leave around 100MB, this seems to work fine.

The `authority` is no longer required ;)

**Comment by MechaRyRy** [comment]
I've added this to our wiki. We should provide a migration from v1 to v2 ASAP to answer these sorts of questions. Closing.
