### ISSUE TITLE
Is it possible to set Headers?

### ISSUE THREAD

**Issue by matecode** [novoda/download-manager#436]
Maybe I'm just missing it, but is it possible to set headers like basic auth?

**Comment by MechaRyRy** [comment]
Hi @matecode it is currently not possible to set custom headers. Is this something you would find helpful? If so, could you open a more complete issue following this format and we will try to plan it into our roadmap. 

```
#### Problem

_Explain the problem that requires addressing_

#### Potential Solution

_Explain high level any potential solutions to the problem as you see it_

#### Impact

_Explain high level what is the impact of fixing (or not fixing) this issue:
- Are there any other components affected?
- Any future feature can benefit from this?
- Is it slowing down something?

```

**Comment by MechaRyRy** [comment]
Thanks for opening that issue @matecode, I'll have a chat with the other contributors on the library and see if we can get a plan of action in place. 

See #437
