### ISSUE TITLE
open API for own OkHttpClient 

### ISSUE THREAD

**Issue by matecode** [novoda/download-manager#437]
#### Problem

setting own headers, using other okhttp interception possibilities is not possible at the moment because the NetworkFileDownloader Implementation is absolutely closed

#### Potential Solution

give an API  to set own HttpClientFactory implementation or something similar 

#### Impact

many developers are already familiar with okhttp api, so its an easy access to all network related things like setting headers

**Comment by zegnus** [comment]
👍 could have a look, yeah

**Comment by MechaRyRy** [comment]
Hi @matecode sorry for the delay but as you can see above we have just merged a PR that contains an open API for the http client. If you would like to have an early look at this you can use the snapshot build that is documented at the bottom of the readme. We'll be shipping this into production when we've done our own round of testing.

**Comment by MechaRyRy** [comment]
Hi @matecode have you had a chance to try out the open API?

**Comment by MechaRyRy** [comment]
Hi @matecode just to let you know that we have released a version with the changes you requested 😄 closing this issue now!

**Comment by matecode** [comment]
Great work, thx
