### ISSUE TITLE
Unexpected download path

### ISSUE THREAD

**Issue by omarsahl** [novoda/download-manager#443]
I used this code to create a `Batch` to download 2 files.

```kotlin
Batch.with(root, DownloadBatchIdCreator.createSanitizedFrom(id), cleanName)
                        .downloadFrom(v.url).saveTo("tbm", vName)
                        .withIdentifier(DownloadFileIdCreator.createFrom("video")).apply()
                        .downloadFrom(a.url).saveTo("tbm", aName)
                        .withIdentifier(DownloadFileIdCreator.createFrom("audio")).apply()
                        .build()
```
The `root` is `/storage/emulated/0/Downloader/`
I expected the path for the `video` file to be `/storage/emulated/0/Downloader/tbm/videoname.mp4` but it was `/storage/emulated/0/Downloader/batch_id_1/tbm/videoname.mp4`
and for the `audio` file I expected it to be `/storage/emulated/0/Downloader/tbm/audioname.m4a` but it was `/storage/emulated/0/Downloader/batch_id_1/tbm/audioname.m4a`
So the generated path for both contains the `batch id` in it due to the following code in `LiteBatchFileBuilder`
```java
StringBuilder absolutePath = new StringBuilder(this.storageRoot.path());
absolutePath = absolutePath.append(File.separatorChar).append(this.downloadBatchId.rawId()).append(File.separatorChar);
if (this.path != null) {
       absolutePath = absolutePath.append(this.path).append(File.separatorChar);
}
absolutePath = absolutePath.append(this.fileName);
```
How can I get the the path I'm looking for which is basically the `root path  + file path + file name` without the `batch id`?

**Comment by MechaRyRy** [comment]
Hi @omar753sahl I'm afraid you need the `batch id` when attempting to retrieve files, the idea being that you could have the same `file id` or `file name` across multiple batches. As for retrieving the path, once you have this information it is trivial to retrieve it from the `DownloadManager`, simply call `getDownloadFileStatusWithMatching(downloadBatchId, downloadFileId)`

**Comment by omarsahl** [comment]
Alright. Thanks @Mecharyry
