### ISSUE TITLE
Addressing Background service constraints for Android O in version 0.3.0

### ISSUE THREAD

**Issue by maboueita** [novoda/download-manager#445]
We are trying to address the issue leading to [this] (https://github.com/novoda/download-manager/issues/244) - and one possible solution could be turning com.novoda.downloadmanager.lib.DownloadService to a JobIntentService. Do you perhaps have insights, ran tests around walking this path, or could suggest a solution, even if temporary, that would leave version 0.3.0 behaving consistently?

P.S: I'm aware of the v2 release, however a migration wouldn't be quite feasible for us before the beginning of November.

**Comment by MechaRyRy** [comment]
Hi @maboueita we understand that a migration to version two may not be possible but unfortunately we are no longer actively supporting version one of this library. If you wish to see any changes to version one I can only suggest you fork it, or alternatively open a PR against the branch on this repository.

Let me know if I can help with anything else.

**Comment by maboueita** [comment]
Hi @Mecharyry, forking an own version would be the idea in this case. My question was more towards if you could provide insights on the impact/side-effects of the change I mentioned.

**Comment by MechaRyRy** [comment]
Ah I see, I'm not that familiar with the impact or side-effects this might have, I've exclusively worked on v2. @joetimmins or @ouchadam may have some ideas?

**Comment by MechaRyRy** [comment]
No response, closing.
