### ISSUE TITLE
Help upgrade from v1 to v2

### ISSUE THREAD

**Issue by tongtanhieu** [novoda/download-manager#469]
Hello,
I have a project using v1, how to update my project to v2. I can't found any document about it. Please help me and thank for your awesome library.

p/s: sorry for my bad English

**Comment by MechaRyRy** [comment]
Hi @tongtanhieu, did you take a look at the demo sample, specifically the `MigrationJob`?https://github.com/novoda/download-manager/blob/release/demo-simple/src/main/java/com/novoda/downloadmanager/demo/migration/MigrationJob.java

**Comment by tongtanhieu** [comment]
thank you very much @Mecharyry , I will take a look into it.
