### ISSUE TITLE
ERROR: Failed to resolve: com.novoda:download-manager:2.3.1

### ISSUE THREAD

**Issue by mspmax** [novoda/download-manager#494]
Hi Guys, 

I'm getting this weird issue since yesterday, it's failing to pull the dependency remotely. This happened on a fresh pull(after removing local build cache). Any idea ? or Am I missing something 🤔 

Cheers!

**Comment by MechaRyRy** [comment]
Hi @mspmax. This is an unfortunate consequence of an account migration that occurred recently. We are trying everything we can at the moment to rectify the issue. I'll feedback here when I know more. Sorry about this!

**Comment by MechaRyRy** [comment]
@mspmax For now we would recommend adding the Bintray maven repo to your build like mentioned in novoda/espresso-support#24

**Comment by mr-archano** [comment]
@mspmax it seems like the issue with JCenter is resolved. You should be able to find the artifact in JCenter like before:
https://jcenter.bintray.com/com/novoda/download-manager/

This means that you could also remove from your buildscript the additional maven repo suggested by @Mecharyry in case you added it.

**Comment by mspmax** [comment]
Thanks! @Mecharyry  and @mr-archano
