### ISSUE TITLE
Deleted notifications are not dismissed

### ISSUE THREAD

**Issue by MechaRyRy** [novoda/download-manager#497]
## Problem
I noticed when testing on `Pixel2` that when starting a download and then triggering a delete that the notification is persisted 😬 

## Solution
Ideally these deleted notifications should be removed from the system notifications. Probably there is a bug in the notification dispatcher.

**Comment by elee20** [comment]
Had same issue.
Seems that LiteDownloadManagerDownloader.java has a bug.
Because "DELETE ALL" button deletes downloadBatch, 
below notification is never updated.

if (downloadBatch != null) {
   notificationDispatcher.updateNotification(downloadBatch.status());
}

**Comment by ouchadam** [comment]
looks like this was fixed by https://github.com/novoda/download-manager/pull/508
