### ISSUE TITLE
Improve demo apps

### ISSUE THREAD

**Issue by amlcurran** [novoda/download-manager#58]
- ~~Split each feature in the extended demo into its own activity (makes it more obvious)~~
- Add a switch to show downloads or batches in the list
- Prettify
- multiple adapters per package so each activity is understandable on it's own
- ~~Add READMEs inside specific packages explaining demos~~

Anything else?

**Comment by amlcurran** [comment]
Add a delete all downloads button to save me having to go the app info all the time

**Comment by amlcurran** [comment]
@blundell https://github.com/novoda/download-manager/pull/69#issuecomment-119146553 :(

**Comment by blundell** [comment]
> but I think that's for another PR

? :)

**Comment by blundell** [comment]
i think in the future we should have multiple adapters per package as well so that it's easily understandable what each demo does on it's own

**Comment by blundell** [comment]
@amlcurran I understand what you mean now!! Yeah this was autoclosed because @xrigau wrote "Fixes #58" in his PR description. I didn't close it.

**Comment by blundell** [comment]
Would be nice to also add README's to each of the separate packages to explain the feature

**Comment by amlcurran** [comment]
OHHH getcha. I've updated the issue now too :+1:

**Comment by blundell** [comment]
we've done a lot of this. Is the only one left multiple adapters?
