### ISSUE TITLE
Remove system downloads code

### ISSUE THREAD

**Issue by amlcurran** [novoda/download-manager#6]
Some of the code can only be run by the system app (such as accessing all downloads), so we can't use it. We should remove it for clarity.

https://github.com/novoda/download-manager/blob/master/library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java#L348
https://github.com/novoda/download-manager/blob/master/library/src/main/java/com/novoda/downloadmanager/lib/Request.java#L149

**Comment by xrigau** [comment]
:+1:
