### ISSUE TITLE
Ensure all resources have a library prefix

### ISSUE THREAD

**Issue by blundell** [novoda/download-manager#7]
We need to prefix with `dm__` so that we don't get clashes when people use the lib and also easier to find all resources.

i.e.

`ic_action_cancel` should be `dm__ic_action_cancel`

**Comment by xrigau** [comment]
```groovy
android {
  resourcePrefix 'dm__'
}
```

http://tools.android.com/tech-docs/new-build-system

**Comment by blundell** [comment]
no! eeevil

**Comment by xrigau** [comment]
reasons or I'm out!

**Comment by blundell** [comment]
when reading source it is not obvious what the actual file name is
