### ISSUE TITLE
First "single" download does not start

### ISSUE THREAD

**Issue by amlcurran** [novoda/download-manager#76]
Steps to repro:
- Go to pause & resume in extended sample
- Press download button

What happens:
- Download does not start until you queue a second download

What should happen:
- Download should start without requiring another download

**Comment by xrigau** [comment]
this is not a real bug, it happens because of this https://github.com/novoda/download-manager/blob/master/demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/DemoApplication.java#L34

**Comment by xrigau** [comment]
as in for the first download that rule doesn't pass so it doesn't download

**Comment by ouchadam** [comment]
maybe fixed by #75 but I'm also working on queued downloads not being triggered in `isAllowedToDownload` but it's a toughie

**Comment by amlcurran** [comment]
fixed by #75 indeed!
