### ISSUE TITLE
Subscribe to specific notifications

### ISSUE THREAD

**Issue by xrigau** [novoda/download-manager#77]
it'd be nice if you could subscribe to, say, download state changes. So instead of getting all the events (i.e. when a file is being downloaded we get events for every chunk of the file that gets downloading), we'd get only state changes (download paused, download started, download failed, download queued...)

**Comment by ouchadam** [comment]
cc @amlcurran is currently working on this

**Comment by amlcurran** [comment]
I am indeedy #97

**Comment by xrigau** [comment]
so we could say this's been fixed?

**Comment by amlcurran** [comment]
I guess we could, I'll let you do the honour

**Comment by xrigau** [comment]
Fixed in #97
