### ISSUE TITLE
Consider not exposing cursors

### ISSUE THREAD

**Issue by amlcurran** [novoda/download-manager#8]
It'd be great to expose value objects not a cursor because then we have type-safety and don't enforce lifecycle constraints on our users (e.g. they need to call `Cursor#close()`)

**Comment by friedger** [comment]
I disagree here, `Cursor` are the way to provide data in Android. What about `CursorList` or a marshaller to get some safety?

**Comment by amlcurran** [comment]
They are, but I don't think they should be :smile:

**Comment by friedger** [comment]
Let's meet at the couch!

**Comment by amlcurran** [comment]
:+1: took me a few seconds to realise what you meant there :+1:
