### ISSUE TITLE
Media scanning, do we need it?

### ISSUE THREAD

**Issue by ouchadam** [novoda/download-manager#90]
Should we continue to support mime type insertion, gallery meta data etc?

I feel like this is something the client should do on download completion?

**Comment by blundell** [comment]
if they choose to download to an external directory i think we should still support it. Obviously this is not relevant when we download to internal private storage.

**Comment by ouchadam** [comment]
is it possible to download to an external location with this library?

This is the class I mean

https://github.com/novoda/download-manager/blob/master/library/src/main/java/com/novoda/downloadmanager/lib/DownloadScanner.java

**Comment by blundell** [comment]
yes, and yes I know of the scanning 

https://github.com/novoda/download-manager/blob/master/library/src/main/java/com/novoda/downloadmanager/lib/Request.java#L130

**Comment by blundell** [comment]
lets supoort & keep this functionality
